runtime: python27
api_version: 1
threadsafe: true
default_expiration: "7d"

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  http_headers:
    Vary: Accept-Encoding

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
  http_headers:
    Vary: Accept-Encoding

skip_files:
- ^node_modules/(.*/)?
- ^config/(.*/)?
- ^public/(.*/)?
- ^scripts/(.*/)?
- ^src/(.*/)?